joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.0
    autorepeat_rate: 0.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.10 
    scale_linear_turbo:
      x: 1.0

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.20 
    scale_angular_turbo:
      yaw: 1.0

    enable_button: 2
    enable_turbo_button: 1

    require_enable_button: true